### PR TITLE
Jersey/Dropwizard LifeCycle Support

### PR DESCRIPTION
**Pull request by Toilal**
When undeploying from Tomcat 8.0.x, log files shows some possible memory leaks. After some investigation, those leaks are REAL.

Currently, JEEBridge overrides `doStop()` and `doStart()` with a noop implementation. 

Dropwizard registers its [Managed](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/Managed.java) objects (DataSource, ThreadPool, ...) into Jetty Server LifeCycle using an adapter called [JettyManaged](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/JettyManaged.java).

By dropping `doStop()` and `doStart()` calls, [ContainerLifeCycle](https://github.com/eclipse/jetty.project/blob/master/jetty-util/src/main/java/org/eclipse/jetty/util/component/ContainerLifeCycle.java) from Jetty Server is not initialized nor shutdown, making [Managed](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/Managed.java) objets from dropwizard not managed at all. Those managed objects are not closed when the application is stopped, causing various possible memory leaks.

This fix the issue by properly starting and stopping the JEEBridge (Fake Jetty Server) when the servlet is loading/unloading (doStart is already called in the application.run method, but doStop() was never called). It also makes the JEEBridge class simpler (hope I didn't break anything about the Attributes things ...)

I've also bumped to latest released dropwizard version, and added an eclipse formatter configuration file.

### CODE REVIEW

**Comment by rvs-fluid-it** [comment]
Thanks for pinpointing the lifecycle related bug.

In the context of a JEE application server it is discouraged to spawn threads in your own application.
(http://stackoverflow.com/questions/533783/why-is-spawning-threads-in-java-ee-container-discouraged) 
Because wizard-in-a-box need to support deployment on Weblogic, I will try to find an alternative solution without creating a threadpool.

Maybe the JEEBridgeFactory can register a ServletContextListener which will notify the JEEBridge of the start and stop of the application.

To be continued

**Comment by rvs-fluid-it** [comment]
Cherry picked two commits. Changed WebApplication so that it will stop each of the ManagedObjects before the WebApplication itself is stopped

**Comment by Toilal** [comment]
What about edit this commit to avoid a ThreadPool to be created, and retrieve a ThreadPool from the J2EE JNDI Context ?

**Comment by rvs-fluid-it** [comment]
I don't think a ThreadPool (inside the webapplication) is needed when
deployed on an application server.
But in case I'm mistaken looking it up using JNDI would indeed probably be
the way to go
(see
http://stackoverflow.com/questions/21516540/custom-thread-on-weblogic-server-11g).
I expect the code to be application server specific so it must be
configurable or pluggable.

**Comment by Toilal** [comment]
I see ... Maybe we should create some kind of "ExecutorServiceFactory" to provide proper ExecutorService implementations for each "supported" container.

**Comment by Toilal** [comment]
From dropwizard sources, there's a ThreadPool for HealthChecks that seems to be required. Internal ThreadPool from Jersey server is probably not required.

**Comment by rvs-fluid-it** [comment]
Can you give me a pointer to the the threading code used by the
HealthChecks?
Thanks

**Comment by Toilal** [comment]
https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/setup/Environment.java#L83-L89

I saw this one by checking very quickly the sources of dropwizard, but there are maybe others ...

**Comment by rvs-fluid-it** [comment]
Good catch.

Quick investigation:

Application -creates-> ServerCommand -extends-> EnvironmentCommand
-creates-> Environment -creates-> LifecycleEnvironment -creates->
ExecutorServiceBuilder ... -creates-> ... Threads

So to swap the thread creation mechanism a lot of classes should be
extended, which could increase the maintenance effort of the project.

But feel free to create an issue for it.
If it becomes a blocking/critical issue, it should be fixed, but as long as
it is not critical, I prefer to leave it like it is ...

**Comment by Toilal** [comment]
True, but let the memory leak on undeploy is critical I think ... 

By merging the remaining commit (https://github.com/Toilal/wizard-in-a-box/commit/af7e8063100eb2d66563c63065a2a9a6878b16c5), it still creates ThreadPool outside of J2EE Container control (they are not monitorable, it's not recommanded, etc...), but it doesn't leak. Those pools are properly shutdown when application is undeployed.

Would you consider again merging as is ?

**Comment by rvs-fluid-it** [comment]
Do you think the memory leak is not completely fixed with commit https://github.com/rvs-fluid-it/wizard-in-a-box/commit/050028bd9ebbce5154164442eef3f93976982958?
I did not test it myself, but can you verify it there is still a memory leak (on Tomcat)?

**Pull request closed without merging**
