### PR TITLE
Add J2EE DataSource Bridge and Configuration classes

### PR DESCRIPTION
**Pull request by Toilal**
This add bridge capabilities from DataSource configured in J2EE Context to Dropwizard DataSource.

This could be enhanced with more documentation and maybe a sample project and some sanity check tests, but it already contains JavaDoc that makes the feature usable.

Related to #3

### CODE REVIEW

**Comment by Toilal** [comment]
I'm not sure why the build fails ...

**Comment by rvs-fluid-it** [comment]
Thanks for the contribution, I will have a look at it tomorrow.

**Comment by rvs-fluid-it** [comment]
Hi,

Can you provide me a developer element
     &lt;developer>
       &lt;name&gt;... &lt;/name&gt;
       &lt;email&gt;...@... &lt;/email&gt;
       &lt;organization&gt;... &lt;/organization&gt;
       &lt;organizationUrl&gt;... &lt;/organizationUrl&gt;
     &lt;/developer&gt;

I like to add you to the list of developers in the pom file.

Regards

**Comment by Toilal** [comment]
``` xml
<developer>
<name>Rémi Alvergnat</name>
<email>toilal.dev@gmail.com</email>
<organization>Pragmasphere</organization>
<organizationUrl>http://www.pragmasphere.com</organizationUrl>
</developer>
```

**Comment by Toilal** [comment]
Thanks for merging ! Could you perform a new release soon ?

**Comment by rvs-fluid-it** [comment]
Hi Rémi,

Thanks for the contribution.
I'll release this evening the new version.

Regards,
Koen

**Pull request merged**
